### ISSUE TITLE
I found samsung loders  edl-samsung-loader-files-2024 (2023 12)

### ISSUE THREAD

**Issue by Destroyarr** [bkerler/Loaders#89]
gsmxt com /edl-samsung-loader-files-2024/ 
[LOADER_SAMSUNG_2024.zip](https://github.com/bkerler/Loaders/files/14548733/LOADER_SAMSUNG_2024.zip)

**Comment by RenateUSB** [comment]
That's a good find!
There are 20 files of the standard ELF format that are not in this repo.
There is 1 file which is:
```
Samsung/G973U_Loader_By_IAASTeam.elf
samsung/000a50e100200000_ab28f20cfb2bd9fe_fhprg.bin
```
There are 10 files with a format that I don't understand.
They are breaking some rules of the ELF standard, but I believe they are functional.
I call these "stub" files because there are only two programs and the bulk of the content is outside where ELF says that it is.
I see 4 files in the repo now that are of this format.
```
lenovo_motorola/0000000002e80000_467f3020c4cc788d_fhprg.bin
lenovo_motorola/001870e102e80000_467f3020c4cc788d_fhprg.bin
nothing/000b80e100020000_467f3020c4cc788d_fhprg.bin
oneplus/0000000000020000_467f3020c4cc788d_fhprg_op10pro.bin
```

**Comment by amourchaouch** [comment]
sm a300fu
